export const ADD_EVENT="ADD_EVENT"
export const SHOW_EVENT="SHOW_EVENT"
export const SET_EVENT="SET_EVENT"
export const EDIT_EVENT="EDIT_EVENT"
export const RESET_EVENT="RESET_EVENT"
export const DELETE_EVENT="DELETE_EVENT"